server:
  port: 8081
  servletPath: /bo-demo-service
spring:
  datasource:
    url: jdbc:oracle:thin:@10.15.191.142:1521:ORCL
    username: CHEQUES
    password: ne0ris
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      failFast: true
      retry:
        ## Intervalo de tiempo inicial entre cada repeticion
        initialInterval: 6000
        ## Incremento exponencial del tiempo de intervalo inicial
        multiplier: 1.5
        ## Tiempo maximo al que puede crecer el intervalo
        maxInterval: 30000
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: INFO
app:
  message:
    error: ERROR APP
  code:
    error: ERROR-01
  propertie:
    test: Valor Propiedad Test
global:
  api:
    basePackage: mx.stmx.bo.demo.controller
    antPattern: /*
    title: DEMO API REST MS ISBAN BO
    description: API REST demo base para backoffice ISBAN
    version: 1.0-SNAPSHOT
    terms: Solo usar como guia
    author: Alan F. Zuñiga Correa
    url: www.test.com
    mail: alan.zuniga@neoris.com
    hystrixMapping: /hystrix.stream
    errorMessage: ERROR GLOBAL
    errorCode: ERROR-00
