server:
  port: 8081
  servletPath: /bo-demo-service
spring:
  datasource:
    url: jdbc:oracle:thin:@10.15.191.142:1521:ORCL
    username: CHEQUES
    password: ne0ris
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      failFast: true
      retry:
        ## Intervalo de tiempo inicial entre cada repeticion
        initialInterval: 6000
        ## Incremento exponencial del tiempo de intervalo inicial
        multiplier: 1.5
        ## Tiempo maximo al que puede crecer el intervalo
        maxInterval: 30000
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: INFO
api:
  error:
    demo1:
      message: ERROR DEMO1
      code: ERROR-01
    demo2:
      message: ERROR DEMO2
      code: ERROR-02
    demo3:
      message: ERROR DEMO3
      code: ERROR-03
    demo4:
      message: ERROR DEMO3
      code: ERROR-03
  propertie:
    demo5: Valor Propiedad DEMO5
  common:
    basePackage: mx.stmx.bo.demo.controller
    antPattern: /*
    title: DEMO API REST MS ISBAN BO
    description: API REST demo base para backoffice ISBAN
    version: 1.0-SNAPSHOT
    terms: Solo usar como guia
    author: Alan F. Zuñiga Correa
    uri: www.test.com
    mail: alan.zuniga@neoris.com
    hystrixMapping: /hystrix.stream
    errorMessage: ERROR GLOBAL
    errorCode: ERROR-00
